<?php
/* Call this file 'hello-world.php' */
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\PrintConnectors\CupsPrintConnector;
use Mike42\Escpos\Printer;

$connector = new CupsPrintConnector("EPSON_LQ_310");
$printer = new Printer($connector);
$printer->text("\n");
$printer->text("                                                         INV-2022-11-01_200820!\n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                          DO.2022-11-01_200820                                 \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                B 12345 KL                                                     \n");
$printer->text("                                                                               \n");
$printer->text("                SEAL/BLACK-01                                                  \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("1.        AWB0001            9      900         SHOES       PT. NIKE INDONESIA \n");
$printer->text("                                                                               \n");
$printer->text("2.        AWB0002            4      100         T-SHIRT    PT. UNIQLO KARAWANG \n");
$printer->text("                                                                               \n");
$printer->text("3.        AWB0003            9      900         SHOES       PT. NIKE INDONESIA \n");
$printer->text("                                                                               \n");
$printer->text("4.        AWB0004            9      900         T-SHIRT    PT. UNIQLO KARAWANG \n");
$printer->text("                                                                               \n");
$printer->text("5.        AWB0005            9      900         SHOES       PT. NIKE INDONESIA \n");
$printer->text("                                                                               \n");
$printer->text("6.        AWB0006            9      900         T-SHIRT    PT. UNIQLO KARAWANG \n");
$printer->text("                                                                               \n");
$printer->text("7.        AWB0007            9      900         SHOES       PT. NIKE INDONESIA \n");
$printer->text("                                                                               \n");
$printer->text("8.        AWB0008            9      900         T-SHIRT    PT. UNIQLO KARAWANG \n");
$printer->text("                                                                               \n");
$printer->text("9.        AWB0009            9      900         SHOES       PT. NIKE INDONESIA \n");
$printer->text("                                                                               \n");
$printer->text("10.       AWB0010            9      900         T-SHIRT    PT. UNIQLO KARAWANG \n");
$printer->text("                                                                               \n");
$printer->text("11.       AWB0011            9      900         SHOES       PT. NIKE INDONESIA \n");
$printer->text("                                                                               \n");
$printer->text("12.       AWB0012            9      900         T-SHIRT    PT. UNIQLO KARAWANG \n");
$printer->text("                                                                               \n");
$printer->text("13.       AWB0013            9      900         SHOES       PT. NIKE INDONESIA \n");
$printer->text("                                                                               \n");
$printer->text("14.       AWB0014            9      900         T-SHIRT    PT. UNIQLO KARAWANG \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("        20:04                                                         23:04    \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("                                                                               \n");
$printer->text("    JONATHAN             STEVEN            PRISKILA            SHAM            \n");
$printer->text("                                                                               \n");
$printer->cut();
$printer->close();
